### ISSUE TITLE
Error thrown on bad network connection instead of returning err to callback.

### ISSUE THREAD

**Issue by kevinmstephens** [log0ymxm/node-harvest#13]
```
{
  "stack": "TypeError: Cannot read property 'statusCode' of null\n    at Request.<anonymous> (/Users/kevinmstephens/FL/biz_int/node_modules/harvest/index.js:94:20)\n    at Request.g (events.js:180:16)\n    at Request.emit (events.js:98:17)\n    at Request.mixin._fireError (/Users/kevinmstephens/FL/biz_int/node_modules/harvest/node_modules/restler/lib/restler.js:202:10)\n    at ClientRequest.<anonymous> (/Users/kevinmstephens/FL/biz_int/node_modules/harvest/node_modules/restler/lib/restler.js:241:14)\n    at ClientRequest.emit (events.js:95:17)\n    at CleartextStream.socketErrorListener (http.js:1547:9)\n    at CleartextStream.emit (events.js:95:17)\n    at Socket.onerror (tls.js:1442:17)\n    at Socket.emit (events.js:117:20)",
  "errMessage": "Cannot read property 'statusCode' of null",
  "name": "TypeError",
  "uuid": "1fdc42fb-bee4-4bec-8a68-8799aaf2a660",
  "process": {
    "pid": 17036
  },
  "os": {
    "hostname": "Kevins-MacBook-Pro.local"
  },
  "level": "crit",
  "message": "caught exception",
  "timestamp": "2014-12-12T01:17:11.182Z"
}
```

**Comment by log0ymxm** [comment]
This should be handled a bit better now with https://github.com/log0ymxm/node-harvest/pull/20
